### ISSUE TITLE
Issue with ReservedItemSlotCore (and cosmetic question)

### ISSUE THREAD

**Issue by kyrthrix** [notnotnotswipez/MoreCompany#6]
Hi! There's an issue with the most recent two updates, 1.5.0 and 1.5.1 where I'm unable to use alt to swap to additional slots, nor f to interact with my flashlight with the mod ReservedItemSlotCore and ReservedFlashlightSlot by FlipMods. I don't know what is changed in the more recent updates to cause this, but I wanted to bring your attention to it.

I also wanted to ask- could you please bring back the blushing emoji head cosmetic? My friends and I really loved it!

**Comment by notnotnotswipez** [comment]
Flushed head was removed for being too large. Not sure what would be going on with ReservedItemSlotCore

**Comment by kyrthrix** [comment]
> Flushed head was removed for being too large. Not sure what would be going on with ReservedItemSlotCore

Awww, we didn't think it was too big...

Well, I'm not sure what it's doing either, but I really hope you can figure it out and fix it! I really want to be able to use both mods! :0

**Comment by SKAREZ** [comment]
**Hey, came back days after to say that so far the bug with [ReservedItemSlotCore](https://thunderstore.io/c/lethal-company/p/FlipMods/ReservedItemSlotCore/) seems to be fixed.**

Played some games with my friends *(more than 7 people)* and no one experienced that bug, may got fixed by FlipsMods since he did like 4 updates so far to his mods.
So now I can play with MoreCompany again :D

**Comment by kyrthrix** [comment]
@SKAREZ  Yes, I saw that!! I'm so glad it got fixed!! :D

Thanks so much for everything you do with this mod @notnotnotswipez !! I love the bigger lobbies and the fun cosmetics! I hope you add more! ❤️
